{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fsarch-common.configMapName" . }}
  namespace: {{ include "fsarch-common.namespace" . }}
  labels:
    {{- include "fsarch-common.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yml: |
    {{- if .Values.config.raw }}
    {{- .Values.config.raw | nindent 4 }}
    {{- else }}
    auth:
      type: {{ .Values.config.auth.type | quote }}
      {{- if eq .Values.config.auth.type "jwt-jwk" }}
      jwkUrl: {{ .Values.config.auth.jwkUrl | quote }}
      {{- else if eq .Values.config.auth.type "oidc" }}
      discovery_url: {{ .Values.config.auth.discoveryUrl | quote }}
      {{- else if eq .Values.config.auth.type "static" }}
      secret: {{ .Values.config.auth.secret | quote }}
      users:
        {{- toYaml .Values.config.auth.users | nindent 8 }}
      {{- end }}

    uac:
      {{- toYaml .Values.config.uac | nindent 6 }}

    database:
      type: {{ .Values.config.database.type | quote }}
      {{- if eq .Values.config.database.type "sqlite" }}
      database: {{ .Values.config.database.database | quote }}
      {{- else }}
      host: {{ .Values.config.database.host | quote }}
      port: {{ .Values.config.database.port }}
      database: {{ .Values.config.database.database | quote }}
      username: {{ .Values.config.database.username | quote }}
      {{- if .Values.config.database.password }}
      password: {{ .Values.config.database.password | quote }}
      {{- end }}
      {{- with .Values.config.database.ssl }}
      ssl:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

    workers:
      websocket:
        auth_token: {{ .Values.config.workers.websocket.authToken | quote }}
        config_check_interval_ms: {{ .Values.config.workers.websocket.configCheckIntervalMs }}
    {{- end }}
{{- end }}
